// frontend/app/login/page.jsx
"use client";

import { useState } from "react";
import { submitForm } from "./actions";
import useWrapperStore from "@/stores/wrapper";

export default function Page(props) {
    const [username, setUsername] = useState("");
    const [password, setPassword] = useState("");
    const setErrorMessage = useWrapperStore((state) => state.setErrorMessage);

    const handleSubmit = async (event) => {
        event.preventDefault();
        if (!username) {
            setErrorMessage("Email is required.");
            return;
        }
        if (!password) {
            setErrorMessage("Password is required.");
            return;
        }
        try {
            const message = await submitForm(username, password);

            if (!message) return;

            if (message.error) {
                throw new Error(message.error);
            }
        } catch (err) {
            setErrorMessage(err.message);
        }
    };

    return (
        <main>
            <section className="container mx-auto px-5 py-5 md:px-10 md:py-10 h-screen">
                <div className="flex flex-col items-center h-full justify-center">
                    <div className="card bg-neutral text-neutral-content w-96">
                        <form className="card-body" onSubmit={handleSubmit}>
                            <h2 className="card-title">LearnIt AI</h2>
                            <p className="text-sm">
                                Kindly login with your account to continue.
                            </p>
                            <div className="mt-2 flex flex-col gap-2">
                                <label className="input input-bordered flex items-center gap-2">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 0 16 16"
                                        fill="currentColor"
                                        className="h-4 w-4 opacity-70"
                                    >
                                        <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6ZM12.735 14c.618 0 1.093-.561.872-1.139a6.002 6.002 0 0 0-11.215 0c-.22.578.254 1.139.872 1.139h9.47Z" />
                                    </svg>
                                    <input
                                        type="text"
                                        className="grow"
                                        placeholder="Username"
                                        value={username}
                                        onChange={(e) =>
                                            setUsername(e.target.value)
                                        }
                                        required
                                    />
                                </label>
                                <label className="input input-bordered flex items-center gap-2">
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        viewBox="0 0 16 16"
                                        fill="currentColor"
                                        className="h-4 w-4 opacity-70"
                                    >
                                        <path
                                            fillRule="evenodd"
                                            d="M14 6a4 4 0 0 1-4.899 3.899l-1.955 1.955a.5.5 0 0 1-.353.146H5v1.5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-2.293a.5.5 0 0 1 .146-.353l3.955-3.955A4 4 0 1 1 14 6Zm-4-2a.75.75 0 0 0 0 1.5.5.5 0 0 1 .5.5.75.75 0 0 0 1.5 0 2 2 0 0 0-2-2Z"
                                            clipRule="evenodd"
                                        />
                                    </svg>
                                    <input
                                        type="password"
                                        className="grow"
                                        required
                                        value={password}
                                        onChange={(e) =>
                                            setPassword(e.target.value)
                                        }
                                        placeholder="Password"
                                    />
                                </label>
                            </div>
                            <div className="card-actions justify-end mt-2">
                                <button className="btn btn-primary w-full">
                                    Login
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </section>
        </main>
    );
}

// frontend/src/routes/login/+page.svelte
<svelte:head>
	<title>Login Page</title>
</svelte:head>

<script>
	import axios from 'axios';

	async function handleSubmit(event) {
        event.preventDefault(); // Prevent the default form submission

        const formData = new FormData(event.target); // Collect form data
        try {
            // Include withCredentials: true in the Axios request configuration
            const response = await axios.post('http://localhost:8000/auth/login/', formData);
            console.log(response.data);

			// Set the access_token in localStorage instead of a cookie
            localStorage.setItem('access_token', response.data.access_token);
        } catch (error) {
            console.error(error);
        }
    }
</script>

<div class="hero min-h-screen">
	<div class="hero-content flex-col">
		<div class="text-center p-4 flex flex-col gap-2">
			<h1 class="text-4xl font-bold text-base-100">LearnIT</h1>
			<h2 class="text-3xl font-bold text-accent">Login Page</h2>
		</div>
		<div
			class="card flex-shrink-0 w-full max-w-sm shadow-2xl bg-base-100 card-compact card-bordered"
		>
			<form on:submit|preventDefault={handleSubmit}>
				<div class="card-body">
					<div class="form-control">
						<label for="email" class="label">
							<span class="label-text">Username</span>
						</label>
						<input
							type="text"
							name="username"
							value=''
							placeholder="example123"
							class="input input-bordered required:border-red-500 invalid:border-red-500 autofill:bg-yellow-200"
						/>
					</div>
					<div class="form-control">
						<label for="password" class="label">
							<span class="label-text">Password</span>
						</label>
						<input
							type="password"
							name="password"
							value=''
							placeholder="Password123"
							class="input input-bordered"
						/>
					</div>
					<div class="form-control mt-6">
						<button class="btn btn-secondary">Login</button>
					</div>
					<!-- {#if form?.error}
						<div class="alert alert-error">
							<svg
								xmlns="http://www.w3.org/2000/svg"
								class="stroke-current shrink-0 h-6 w-6"
								fill="none"
								viewBox="0 0 24 24"
								><path
									stroke-linecap="round"
									stroke-linejoin="round"
									stroke-width="2"
									d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z"
								/></svg
							>
							<span class="error">{form?.message}</span>
						</div>
					{/if} -->
				</div>
			</form>
		</div>
	</div>
</div>
